### PR TITLE
port buildbot_travis to buildbot nine

### PR DESCRIPTION
**Pull request by tardyp**
The UI needs to be rewritten, but we have a working travis spawner, with git scm.

I don't want to spend too much time testing with svn, but I dont think this should be hard.

I think we should eventually push this project to upstream.

This branch still needs some changes to upstream: 
https://github.com/tardyp/buildbot/tree/travis

### CODE REVIEW

**Comment by tardyp** [comment]
added some nice configuration U via plugins.

image

**Comment by sa2ajj** [comment]
So can we do something about the license?

If it were changed, I could look into taking bits and porting them to Buildbot's master...

**Comment by Jc2k** [comment]
Wow, that UI looks slick!

I've made an eight branch and changed the licence there to the same one as buildbot.

@tardyp - if it's OK with you i'll merge this as is, and then make the same licence change? (I figure the merge/rebase would be annoying)

Going forward, given everyone looking at this is already a buildbot committer, I could move the repo there?

Or we could aim to merge it all upstream?

**Comment by tardyp** [comment]
Jc2k, you can merge it as is.
I am okay for GPLv2 for my contributions

I am also okay for merging this all in upstream (probably mark it experimental though)

**Pull request merged**
